apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: account-mongodb
  namespace: springcloud
  labels:
    name: account-mongodb
spec:
  replicas: 1
  template:
    metadata:
      labels: 
        name: account-mongodb
    spec:
      terminationGracePeriodSeconds: 120
      containers:
      - name: account-mongodb
        image: sqshq/piggymetrics-mongodb
        imagePullPolicy: IfNotPresent
        resources:
          limits:
            cpu: 1000m
            memory: 2000Mi
        env:
        - name: INIT_DUMP
          value: account-service-dump.js
        - name: MONGODB_PASSWORD
          value: admin
  
